export const START_AUTHENTICATION = "START_AUTHENTICATION";
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";

export const LOG_OUT = "LOG_OUT";
